### PR TITLE
Users can now set a delay between each scan in the config page

### PR DESCRIPTION
**Pull request by mmaasbo**

### CODE REVIEW

**Comment by djv2** [comment]
this is between each new location scan right? 

is it possible to create a delay between each intermittent scan at 1 location (1 circle)? that might help with temp IP bans

**Comment by nborrmann** [comment]
@djv2 i also think this would be more useful

**Comment by Craggles17** [comment]
Could we merge this anyway? I think this feature will still help with ip bans.

**Comment by mmaasbo** [comment]
It seems like the login-loop was the cause of the ip-bans, so this feature may not be necessary. It should be possible to set a delay between each substep. I'l look into it.

**Pull request closed without merging**
