### PR TITLE
Add optional webhook support when enabled

### PR DESCRIPTION
**Pull request by DenL**
Add a webhook thread to send data to webhook when optional -wh arguments are supplied. Payload format/protocol is the same as it was in PokemonGo-Map so that it is compatible with tools designed to run with it.

### CODE REVIEW

**Comment by snicker** [comment]
cool, looks better than #209 with the dedicated thread, plus #209 was never merged and now has conflicts. I'll close in favor of this (hopefully @favll will merge this one)

**Comment by nborrmann** [comment]
I don't like the command line flag. Can you make it configurable through the Web UI?

**Comment by ercoman** [comment]
Ugh I'm trying to set up this but I cannot. I've installed pokealarm with the alarms.json file to use pushbullet, changed the files in the pogom files but I only recieve the alarm of "PokeAlarm activated! We will alert you about pokemon" nothing else. 

Something I'm missing?

**Comment by DenL** [comment]
I could, but I don't have the code that deals with changes to config after the program is started. I will close this after a couple days if I can't find the time to add it. Thanks.

**Comment by ercoman** [comment]
Works like a charm for me, thanks!

**Pull request closed without merging**
