### PR TITLE
large disappear time fix

### PR DESCRIPTION
**Pull request by seikur0**

### CODE REVIEW

**Comment by Mickey32111** [comment]
I think this works. :)

**Comment by Mickey32111** [comment]
Do I need to rollback my 64bit change?

**Comment by seikur0** [comment]
I guess, it doesn't matter that much, but you can.

**Comment by Infernoman** [comment]
it only works to a certain extent. this doesnt not handle them correctly. we need to figure out how to get the proper despawn time.

**Comment by seikur0** [comment]
They were never correct despawn times in the first place @Infernoman... Before the overflow they were negative and now they're positive. It handles them the same as it did before.

**Comment by CuRleGit** [comment]
Are the spawns with 590+ hours legitimate spawns? If so, this change will hide some spawned Pokemon?

Is it possible to instead change spawn Pokemon spawns, with higher spawn times, to 15 minutes? So they are at least displayed (and then removed after the minimum (15 minute) spawn time).

**Comment by seikur0** [comment]
They are legitimate spawns and this change will show them to disappear in 15 minutes, just like it did before for the negative and also legitimate spawn times (you probably didn't notice ;) )

fun fact: pokeminer throws them away and only displays the times, when they go below 15 minutes. spawnpoints, that spawn a pokemon for 1 hour and change it after that never have a positive time below 15 minutes->never displayed in pokeminer. https://github.com/modrzew/pokeminer/issues/220

**Comment by Cromi38** [comment]
This is going to sound really dumb, but how do I go about recompiling?  I am pretty new to python, I'm decent with C++

**Comment by dikkedeur** [comment]
this fix works as it seems, i manually added it, dropped my db and restarted my scan, and everything looks fine

**Comment by ghvanderweg** [comment]
This works great. Come on guys, get this merged already...

**Comment by khag7** [comment]
I'm confused by this "fix"... Aren't the spawnpoints causing this problem 30, 45, or 60 minute points? They're never 15 right? Wouldn't it make more sense to set it to 30 minutes since we know it will be there at least that long? We can't safely guess 45 or 60, but surely we can say they'll be at least 30.

**Comment by nborrmann** [comment]
>Wouldn't it make more sense to set it to 30 minutes since we know it will be there at least that long?

We don't. It could be 15 minutes and 1 second.

**Comment by seikur0** [comment]
Could even be just one second for 1x60min spawn points.

**Comment by khag7** [comment]
Are you guys suggesting there are spawnpoints that last lengths of time other than 15, 30, 45, or 60? There are literally millions of users and nobody has ever suggested this before. You're definitely right, we don't "KNOW" for sure, but we *know* in the sense that its accurate enough to say they'll be there at least 30 minutes. just saying.

**Comment by ccmawo** [comment]
mysql> delete  from pokemon where TIMESTAMPDIFF(minute,UTC_TIMESTAMP(),disappear_time)>30;

deletes all pokemons with disappear_time greater than 30 minutes

**Pull request merged**
