### PR TITLE
Add my location feature

### PR DESCRIPTION
**Pull request by danhart**
Issue: https://github.com/favll/pogom/issues/258

Allows map users to directly track their current GPS location on the map. This code was taken from the original PokemonGo-Map, but significantly refactored/improved. One particular improvement is that it uses `navigator.geolocation.watchPosition`, in order to keep the blue location marker up-to-date. The original PokemonGo-Map version only used `getCurrentPosition`, which meant you had to keep tapping the location icon to get an update.

I've tested it fairly well on iOS Safari (latest) and had good results.

### CODE REVIEW

**Comment by Mickey32111** [comment]
This isn't working for me, I'm not sure if I've merged incorrectly though. I get no blue location marker. All the GPS button does it zoom the map in.

**Comment by PhDeez** [comment]
@Mickey32111 It has been mentioned in other threads that for modern browsers to ALLOW geo-location you need to either:
be on localhost (ie: ssh to server, setup port forwarding and browse that way OR ngrok)
or over a secured connection like SSL.  pogom does not have that support baked in HOWEVER you can place an nginx setup in front of pogom and setup a certificate

**Comment by danhart** [comment]
@PhDeez I have been testing this on iOS Safari and iOS Chrome and it works well. The map instance I'm running is not HTTPS and I'm not using SSH for port forwarding or anything like that. It's just simply accessible via http://<public-ip>:5001.

@Mickey32111 Which OS did you test this on? My guess is that the security restrictions for geo-location are stricter on Android.

**Comment by Mickey32111** [comment]
@danhart @PhDeez my instance is running in a DMZ with a domain resolving at port 80 on the IP

**Comment by bigblackqueh** [comment]
Great the geolocation works perfectly. Is it possible to enable a scan around your location by default such that it follows you wherever you go?

**Comment by danhart** [comment]
@Mickey32111 but are you opening it on Android or iOS? Only tested on iOS.

**Comment by st0nec0ld** [comment]
Tested it on Android and ngrok...

https://xxxxxx.ngrok.io > works, but i cant add scan location
http://xxxxxx.ngrok.io > dont work, but i can add scan location

**Comment by danhart** [comment]
Thanks @st0nec0ld. Could you try testing master on https? Trying to determine if that's an issue introduced by this change or not. I just tested adding scan locations on iOS and that still works fine.

**Comment by Mickey32111** [comment]
@danhart 

Tested on:
- iOS 10 Beta in Chrome and Safari (doesn't really matter, all runs WebKit).
- Chrome Dev Build on macOS Sierra Beta.

**Comment by RafaelKaczmarczyk** [comment]
Tested it on iPhone with Chrome on a non SSL Public Server with Port 5002

Works fine!

**Comment by st0nec0ld** [comment]
Tested it again. Works over https with pagekite tunnel. Maybe ngrok is to slow.

**Comment by lax20attack** [comment]
This was already done, but the PR was never merged.

https://github.com/favll/pogom/pull/302

**Comment by Mickey32111** [comment]
I moved my instance to the azure cloud, and set it to force https, working great now :)

**Comment by joeubi** [comment]
Works like a charm using Nginx!

**Comment by favll** [comment]
So does this really work via `http://[public_ip]:[port]` without ssl certificate and domain? What's the difference between #302 and this solution? (I haven't looked at the code).

**Comment by joeubi** [comment]
Works for me using a self-signed cert....

**Comment by danhart** [comment]
@favll the SSL certificate and domain is only an issue for Android. Android requires SSL. It was never a problem for iOS. I can add something in to this PR that hides the location button if the user is on Android without SSL if you like?

**Here's what it looks like on iOS Safari:**
img_4607

**Pull request closed without merging**
