### PR TITLE
Added MySQL in command line params

### PR DESCRIPTION
**Pull request by marbink**
Basic implementation of MySQL using peewee. Configuration using web interface is missing. But this could be a good point from where to start.

Example:
runserver.py --db-type mysql --db-name pokemon --db-user root --db-pass password --db-host localhost

### CODE REVIEW

**Comment by nborrmann** [comment]
Can you make it use a connection string? Then it's just one command line parameter

http://docs.peewee-orm.com/en/latest/peewee/database.html#connecting-using-a-database-url

**Comment by marbink** [comment]
Implemented connection string. One parameter (-db).

Example:
runserver.py --db mysql://user:passwd@ip:port/my_db

**Comment by vinsilsim** [comment]
Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/home/pogom/pogom/app.py", line 17, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "/home/pogom/pogom/models.py", line 19, in <module>
    db = connect(args.db)
NameError: name 'connect' is not defined

help me?

**Comment by marbink** [comment]
I'm from phone now, i can't test. it should be ok now.

**Comment by stlmikey80** [comment]
Can't wait for this.. be nice to be able to use this script on 2 computers with 2 different ips..

**Comment by eggins** [comment]
Epic... This will probably work perfectly for a docker install :D

**Comment by stlmikey80** [comment]
well i went ahead and added the edits.  It's not perfect needs work...  When you refresh it will start the timer over for the pokemon...

**Comment by marbink** [comment]
@stlmikey80  I'm not experiencing any problem, can you explain me better how to reproduce it? Thanks.

**Comment by compuguy** [comment]
The dockerfile should also be updated to allow passing of the command line options as well.

**Comment by hemsleyk** [comment]
This would still be weak for Docker due to the reliance on web UI for config. The other map allows headless SQL writers configured via docker environment variables / docker run command with a single (or load balanced) web UIs that only read data from SQL.

Huge step in the right direction though, getting MySQL working is core to any distributed workload.

**Comment by favll** [comment]
Has someone tested this with PostgreSQL?

**Pull request merged**
