### PR TITLE
Added lastseen column to stats page

### PR DESCRIPTION
**Pull request by luzannew**
Feature from a comment in issue #326

### CODE REVIEW

**Comment by Empty2k12** [comment]
This is very useful! Would like to see it get merged!

**Comment by SumBeam** [comment]
Hmm, there's a little 'bug'. It shows the lastseen datetime in UTC format, and not your local timezone.

I'm not familiar with Python and the libraries that are used, so i'm not sure how to fix it. I could do it in javascript, but also with a package 'pytz' for python.

Any ideas?

**Comment by Mickey32111** [comment]
Works brilliantly. Thank you :)

**Comment by favll** [comment]
94ea0ba32111578468e9e800cc276fb8274e11d9

**Pull request closed without merging**
