### PR TITLE
negative tth overflow fixed

### PR DESCRIPTION
**Pull request by seikur0**

### CODE REVIEW

**Comment by compuguy** [comment]
@seikur0 looks good on my box.

**Comment by fishsofresh** [comment]
@seikur0 im sorry but i have no knowledge of programming and can follow basic instructions. but how do you use the file change provided ?

**Comment by compuguy** [comment]
@fishsofresh He's sumitted a pull request to push his change to the repo. Once that is approved, it will be merged to the head of master. Stop running the worker/server and do a git pull to get the latest change. This fix doesn't remove the entries that have been added to the sqlite db already, just new pokemon that show up.

**Comment by fishsofresh** [comment]
@compuguy thank you very much for the info .hope you have a great day .

**Comment by seikur0** [comment]
@compuguy: Does it work for you? Cause for me it changes nothing. So I guess it's being sent as 32bit by the server already. I guess we have to live with these huge positive numbers for now.

**Comment by compuguy** [comment]
@seikur0 It looked like it was working, but before I could get a good run on it, my servers ip was banned. It looks like you attempted another fix, #266. I'll try that

**Pull request closed without merging**
