### PR TITLE
Protect website with a password

### PR DESCRIPTION
**Pull request by DPr00f**
Option to protect the website with a password if set in the config.

### CODE REVIEW

**Comment by bottlebug** [comment]
Working. But breaks "Hide common Pokemon: " and "Show a heatmap of pokemons:"

**Comment by DPr00f** [comment]
@bottlebug I'm using it, with "Hide common Pokemon" and heatmap with no problems. But it has conflicts now, I'll just close it as no one seemed really interested in this feature.

**Comment by bottlebug** [comment]
Would support this to be continued. I'm running a server for a group of friends so was quite happy to see a way to restrict access to my server.

**Comment by DPr00f** [comment]
@bottlebug fixed the conflicts and reopened the PR https://github.com/favll/pogom/pull/337

**Pull request closed without merging**
