### PR TITLE
Add GPS Tracking

### PR DESCRIPTION
**Pull request by lax20attack**
Add gps tracking #258

### CODE REVIEW

**Comment by Mickey32111** [comment]
Is this stable enough to push to my build?

**Comment by lax20attack** [comment]
@Mickey32111 , with the latest bug fix it should be. Working fine for me. Tested everything I could think of.

**Comment by herculys** [comment]
what it does?
nice to see you here pokeadvisor guy.

**Comment by lax20attack** [comment]
@herculys, Hi! This implements Location tracking as described in https://github.com/favll/pogom/issues/258

When enabled, it will follow you around with a little blue dot.

Unfortunately, you will need to set up SSL or run from localhost since most modern browsers will not allow Geolocation on unsecured connections.

**Comment by PhDeez** [comment]
@lax20attack So, from a user stand point I will say that I was super frustrated with PokemonGo-Map having geolocation capability but it not working.  Now that I know geo-location is disabled on non-ssl connections maybe the config page can "offer" geolocation as an option to be enabled with the disclaimer of "you need a secure connection or to be on localhost for this to work" and a link on how to setup something like nginx... ?

**Comment by nborrmann** [comment]
@PhDeez Setting up nginx + SSL isn't something an amateur can do with a guide. That's part of the reason why I'm bearish on the whole geolocation thing. Too much hassle for little benefit.

**Comment by PhDeez** [comment]
@nborrmann Agreed, however I do think setting up an ssh tunnel is much easier and most people could handle that.  Furthermore, making it an option to enable/disable (with it disabled by default) makes it so not everyone even has to use it...

**Comment by PhDeez** [comment]
I just wanted to jump in here for those people looking for something like this...

I just started using the PogomBOT yesterday and when you receive a location you can click on the map which then shows your geolocation compared to where the coordinates are of the notified Pokemon (and can also hit drive there to open in your map application).

Point is... if you don't want to have to deal with connecting to localhost for the map and don't want to set up SSL using Telegram is a good option.

**Comment by compuguy** [comment]
@nborrmann I was looking into using docker-compose with this nginx container: https://hub.docker.com/r/jwilder/nginx-proxy/ to add ssl capabilities easily. This is the current docker-compose file I've been working on: compuguy/719745fcc89b20476150678174f00cd7

**Comment by favll** [comment]
Thank you for your work, but as @nborrmann said this would make the setup too complex.

**Pull request closed without merging**
