### PR TITLE
API version 0.51.0

### PR DESCRIPTION
**Pull request by Paralysing**
- Connects to hashing server for 0.51.0
- Request delay

Adds -k and -sd arguments
-k is for the hashing key, -sd is for delaying map requests to stay inside the hashing ratelimits.

### CODE REVIEW

**Comment by favll** [comment]
Will take a closer look at this tomorrow or the day after. Thank you for your work :) 👍

**Comment by Paralysing** [comment]
Thanks, if you want me to fork and then apply patches so it shows less changed files, just tell me, I just copied my repo and pasted it into the fork.

**Comment by Paralysing** [comment]
Messed up on the fork, will refork and modify, accidentally submitted the old pogom.

**Comment by Paralysing** [comment]
@favll Please review #418 , messed up on this fork and accidentally submitted the wrong version of the code.

**Pull request closed without merging**
