### PR TITLE
Enables desktop notifications.

### PR DESCRIPTION
**Pull request by JavierParra**

### CODE REVIEW

**Comment by stlmikey80** [comment]
thanks working good..  here how to add Notify Pokemon when clicking on them

open maps.js..  

find
<a href='#' onclick='removePokemon(\"" + id + "\")')>Hide " + name + "s</a>\

below it add
<a href='#' onclick='clicknotifyPokemon(\"" + id + "\")')>Notify " + name + "s</a>\


Find:

function removePokemon(id) {
    var selected=$selectExclude.val();
    selected.push(id.toString());
    $selectExclude.val(selected);

    $selectExclude.change();
}

below it add

function clicknotifyPokemon(id) {
    var selected=$selectNotify.val();
    selected.push(id.toString());
    $selectNotify.val(selected);

    $selectNotify.change();
}

**Comment by EiTeR94** [comment]
i got a internal error when i try to add your 2 files modified to the current release. why?

**Comment by JavierParra** [comment]
@stlmikey80 Thanks. I didn't think to add that feature. Will do.
@EiTeR94 I wouldn't know why you get a 500 error. Most of the changes are in the javascript which is not executed by python so any errors should be client side.

**Comment by EiTeR94** [comment]
i fixed the 500 error, but the notification doesnt work, nothing change with your new file

**Comment by pixmaip** [comment]
@EiTeR94 I copied his files and it works perfectly for me. 

To add a notification sound just add:
```javascript
var audio = new Audio('local/path/to/the/sound.mp3');
```
Then add this to play the sound:
```javascript
audio.play();
```

**Comment by EiTeR94** [comment]
Well i got that with his master release : 
capture

**Comment by DavidBindloss** [comment]
Played around with this and it's working for me.

**Comment by EiTeR94** [comment]
well, ok, it doesnt work on my firefox

**Comment by JavierParra** [comment]
@EiTeR94 Do you have any error in your javascript console? As per iOS notifications I'm not sure. Apparently iOS doesn't use the standard Notifications API (which makes sense because Safari would need to be kept running)

**Comment by EiTeR94** [comment]
and on chrome for iphone, can you make a notification pop up?

**Comment by dudeman999** [comment]
@pixmaip Care to explain where exactly you should add those lines to get notification sounds?

I got everything else running, but I really want the noise.

**Comment by pixmaip** [comment]
@dudeman999 
Add this line at the top of map.js:
```javascript
var audio = new Audio('static/sound/ding.mp3');
```
then find this line:
```javascript
notificationTitle = notifications[notificationPid].pokemon_name + ' appeared on map.';
```
and add this just after:
```javascript
audio.play();
```
then find this line:
```javascript
notificationTitle = notificationsLength+' watched pokémons appeared on map.';
```
and add this just after:
```javascript
audio.play();
```

For the notification sound I used [this ding.mp3](https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/static/sounds) from another map project.

**Comment by JavierParra** [comment]
@EiTeR94 Do you have any error in your javascript console? As per iOS notifications I'm not sure. Apparently iOS doesn't use the standard Notifications API (which makes sense because Safari would need to be kept running)

**Comment by dudeman999** [comment]
@pixmaip you are a scholar and a gentleman. Thank you very much.

You or anyone else wouldn't happen to know how to make the map accessible from mobile phones would you? I am also struggling to find a guide on how to do so.

**Comment by Gee19** [comment]
@dudeman999 Just find a server to host it for yourself or your friends

**Comment by dudeman999** [comment]
@Gee19 I was able to do it with the other maps only because they had "Deploy to ----" buttons in their wiki that made it easy to set it up. I'm currently looking into portforwarding. Is there another manner in which I should try?

**Comment by pixmaip** [comment]
@dudeman999 @Gee19 This map doesn't have a native ngrok integration, what you can do is install ngrok yourself. The problem is that if you are able to do this, the interface doesn't work on mobiles (all you can see is the side panel).

**Comment by Gee19** [comment]
@dudeman999 You could try hosting it from home using a service like noip or dyndns. You may have to mess with the layout to get it to display properly on mobile

**Comment by EternisRequiem** [comment]
Hmmm I tried to edit the files and run the server, but now no pokemon whatsoever are showing up in the map itself.  (Then again I'm pretty darn new to this whole thing...)

**Comment by pixmaip** [comment]
@EternisRequiem Did you add ptc accounts ?

**Comment by EternisRequiem** [comment]
This was working a few moments ago before I edited the files that were listed in the commits he posted, in other words.  Then again maybe I did something wrong/weird?  But so far everything is working other than the actual pokemon appearing.

**Comment by pixmaip** [comment]
Try to start the server in debug mode (add ```-d debug```) and see if you have any errors.

**Comment by EternisRequiem** [comment]
Would it show up as error somewhere?  (sorry there's a lot of lines of things to read!)

**Comment by Gee19** [comment]
@EternisRequiem In the console/command line

**Comment by EternisRequiem** [comment]
@gee19 yes I was able to do it, but I didn't see anything that was specifially coming up as an "error", I did see certain things show up as "Debug" but I'm not sure what I should be reporting.

**Comment by pixmaip** [comment]
@EternisRequiem Go to [pastebin.com](http://pastebin.com) and paste a fair piece of your log (not the entire thing!), then give us the link to your pastie.

**Comment by EternisRequiem** [comment]
Okay, I don't know what I did to get this to work, re-downloaded it.  Now I'm just getting 
2016-08-09 19:31:55,390 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?

**Comment by nborrmann** [comment]
Thanks for the PR but i merged #195 instead.

**Pull request closed without merging**
