### PR TITLE
Add deploy button to Jelastic

### PR DESCRIPTION
**Pull request by dreadpiratejhonatan**
Added a button to automatically set up the map on cloud.

### CODE REVIEW

**Comment by nborrmann** [comment]
Currently testing, it just stays at that point forever.

image

**Comment by Teamtyler2** [comment]
Can i test this as well?

**Comment by dreadpiratejhonatan** [comment]
@Teamtyler2 Of course you can! @nborrmann I've tested it with the Colombia e Brazil service providers, and both worked fine. Which one have you used when you get this screen?

**Comment by Teamtyler2** [comment]
Where can i download the button at?

**Comment by eugenio412** [comment]
Awesome! it works for me also! and it's so dumb proof! Italy service as well!

**Comment by dreadpiratejhonatan** [comment]
@Teamtyler2 Go [here](https://www.reddit.com/r/pokemongodev/comments/4xy8p9/setting_up_easily_pogom_on_cloud/) for instructions on how to use it.

**Comment by nborrmann** [comment]
I used the one in Germany.

**Comment by eugenio412** [comment]
But I got banned in the blink of an eye

**Comment by nborrmann** [comment]
I edited the files to only use this repo instead of the @dreadpiratejhonatan one. Can someone check if everything still  works?

**Comment by dreadpiratejhonatan** [comment]
@nborrmann You forgot to make the docker image file, so it isn't working.

**Comment by EnigmaDay1** [comment]
Is it always possible to deploy the app on Jelastic ?

I tried many times with different providers but it didn't work.

Thanks for help.

**Pull request merged**
