### PR TITLE
Telegram bot for notification

### PR DESCRIPTION
**Pull request by eugenio412**
The bot is scanning the database for any change, if a new pokemon is inserter in the db it sends a message. 
The message is sent only if the user activated the notification of the desired pokemon. 
Now it's time to go back to my thesis.

### CODE REVIEW

**Comment by eugenio412** [comment]
I have a fork on https://GitHub.com/eugenio412/pogom , add a pull request there

**Comment by aaronr0207** [comment]
cant acces stats page, cloned your fork. "Internal server error" any suggest? miss something?

**Comment by nborrmann** [comment]
This seems to be a standalone script, right?

I don't think adding it to the repo makes much sense.

**Comment by eugenio412** [comment]
ok, I'm working on it

**Comment by eugenio412** [comment]
@nborrmann you can try it yourself and decide if it's the case to add it to the readme

**Pull request closed without merging**
